In [1]:
import pandas as pd

from global_macro import global_macro_df

In [2]:
sp_table = pd.read_csv('sp500_table.csv')
sp_table

,Date,Ticker,Total Revenue,Gross Profit,Operating Income,Net Income,Diluted EPS,Research And Development,Total Assets,Total Liabilities Net Minority Interest,Total Debt,Stockholders Equity,Cash And Cash Equivalents,Ordinary Shares Number,Operating Cash Flow,Free Cash Flow,Capital Expenditure
0,2025-12-31,MMM,2.494800e+10,9.957000e+09,4.791000e+09,3.250000e+09,6.00,1.169000e+09,3.773300e+10,3.298600e+10,1.260200e+10,4.702000e+09,5.235000e+09,530279131.0,2.306000e+09,1.396000e+09,-9.100000e+08
1,2024-12-31,MMM,2.457500e+10,1.012800e+10,4.822000e+09,4.173000e+09,7.55,1.085000e+09,3.986800e+10,3.597400e+10,1.304400e+10,3.842000e+09,5.600000e+09,539470303.0,1.819000e+09,6.380000e+08,-1.181000e+09
2,2023-12-31,MMM,2.461000e+10,9.627000e+09,-1.072500e+10,-6.995000e+09,-12.63,1.154000e+09,5.058000e+10,4.571200e+10,1.675100e+10,4.807000e+09,5.735000e+09,552581136.0,6.680000e+09,5.065000e+09,-1.615000e+09
3,2022-12-31,MMM,2.616100e+10,1.030800e+10,1.916000e+09,5.777000e+09,10.18,1.160000e+09,4.645500e+10,3.168500e+10,1.685500e+10,1.472200e+10,3.655000e+09,549245105.0,5.591000e+09,3.842000e+09,-1.749000e+09
4,2021-12-31,MMM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2484,2021-12-31,ZTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2485,2022-12-31,ZTS,8.080000e+09,5.626000e+09,2.928000e+09,2.114000e+09,4.49,5.390000e+08,1.492500e+10,1.052200e+10,8.090000e+09,4.405000e+09,3.577000e+09,463808059.0,1.912000e+09,1.326000e+09,-5.860000e+08
2486,2023-12-31,ZTS,8.544000e+09,5.983000e+09,3.069000e+09,2.344000e+09,5.07,6.140000e+08,1.428600e+10,9.295000e+09,6.755000e+09,4.997000e+09,2.039000e+09,458367358.0,2.353000e+09,1.621000e+09,-7.320000e+08
2487,2024-12-31,ZTS,9.256000e+09,6.537000e+09,3.392000e+09,2.486000e+09,5.47,6.860000e+08,1.423700e+10,9.467000e+09,6.744000e+09,4.770000e+09,1.985000e+09,448473073.0,2.953000e+09,2.298000e+09,-6.550000e+08
2488,2025-12-31,ZTS,9.467000e+09,6.801000e+09,3.597000e+09,2.673000e+09,6.02,6.980000e+08,1.546700e+10,1.213600e+10,9.238000e+09,3.331000e+09,2.310000e+09,424927535.0,2.904000e+09,2.283000e+09,-6.210000e+08

In [6]:
global_macro = pd.read_csv('global_macro_df.csv')
global_macro

,Date,Policy_Rate,Inflation_CPI,M2_Money_Supply,Unemployment_Rate
0,1947-01-01,NaN,21.480,NaN,NaN
1,1947-02-01,NaN,21.620,NaN,NaN
2,1947-03-01,NaN,22.000,NaN,NaN
3,1947-04-01,NaN,22.000,NaN,NaN
4,1947-05-01,NaN,21.950,NaN,NaN
...,...,...,...,...,...
3566,2026-06-01,NaN,NaN,NaN,4.2
3567,2026-06-01,NaN,NaN,23155.2,NaN
3568,2026-06-01,NaN,332.568,NaN,NaN
3569,2026-06-01,3.63,NaN,NaN,NaN
3570,2026-07-01,3.63,NaN,NaN,NaN